#!/bin/bash

# In this part we do a pass of rate-limiting data-dropping 1-hop runs,
# and compare the performance of different memtable and compaction
# modes: 2x2 (radix=1, 2-way memtable, 2 bg compaction threads) and
# 1x1 (radix=0, 1-way memtable, 1 single bg compaction thread).

# We keep the IO speed fixed at 5.33GiB/s per 32 compute nodes,
# or 5.33MiB/s per core.

for n in 0 1; do
for r in 1 2 3 4 5 6; do
std="--constraints haswell --experiment sc18d --iterations 1 \
--overcommit enable --tag rc33-try3-${n}radix --tests deltafs --skipreads \
--env XX_IGNORE_DIRS=fields:hydro:rundata:names \
--env XX_SKIP_SAMP=1 \
--env XX_SH_THREE_HOP=0 \
--env XX_HG_PROTO=bmi+tcp \
--env XX_ALWAYS_SHUFFLE=0 \
--env XX_BYPASS_CH=1 \
--env XX_IMD_RATELIMIT=5588910 \
--env XX_IMD_DROPDATA=1 \
--env XX_LG_PARTS=$n \
--env XX_BF_BITS=12"

eval ../vpicexpt_gen.pl ${std} --run $r --dw bw .

done
done
