#!/bin/bash

# In this part we do a pass of rate-limiting data-dropping 1-hop runs,
# and compare 2 rates: 8 MiB/s and 3 GMiB/s per core.

for rl in 8388608 3145728; do
for r in 1 2 3 4 5 6; do
std="--constraints haswell --experiment sc18d --iterations 1 \
--overcommit enable --tag rc33-try2-$(($rl/1024/1024))mb --tests deltafs --skipreads \
--env XX_IGNORE_DIRS=fields:hydro:rundata:names \
--env XX_SKIP_SAMP=1 \
--env XX_SH_THREE_HOP=0 \
--env XX_HG_PROTO=bmi+tcp \
--env XX_ALWAYS_SHUFFLE=0 \
--env XX_BYPASS_CH=1 \
--env XX_IMD_RATELIMIT=$rl \
--env XX_IMD_DROPDATA=1 \
--env XX_BF_BITS=12"

eval ../vpicexpt_gen.pl ${std} --run $r --dw bw .

done
done
