#!/bin/bash

# Test different rpc sizes. 1-hop code. 1 outstanding rpc.

# We keep the IO speed fixed at 5.33GiB/s per 32 compute nodes,
# or 5.33MiB/s per core. We don’t drop data.

for sz in 32 4 1; do
for r in 1 2 3 4 5 6; do
# deltafs w/o memtable sort
std="--constraints haswell --experiment sc18d --iterations 1 \
--overcommit enable --tag rc40-try12-unsorted-1out-${sz}k --tests deltafs --skipreads \
--env XX_IGNORE_DIRS=fields:hydro:rundata:names \
--env XX_SKIP_SAMP=1 \
--env XX_SKIP_SORT=1 \
--env XX_NO_PRE_FLUSH=0 \
--env XX_NO_PRE_FLUSH_WAIT=0 \
--env XX_NO_PRE_FLUSH_SYNC=0 \
--env XX_IMD_RATELIMIT=5588910 \
--env XX_BG_PAUSE=1 \
--env XX_SH_THREE_HOP=0 \
--env XX_HG_PROTO=bmi+tcp \
--env XX_ALWAYS_SHUFFLE=0 \
--env XX_RPC_BUF=$((sz*1024)) \
--env XX_RPC_DEPTH=1 \
--env XX_BYPASS_CH=1"

eval ../vpicexpt_gen.pl ${std} --run $r --dw bw .

done
done

exit 0
