#!/bin/bash

# These are Haswell, ppn-sclaing, shuffle-only runs.

for exp in pd18i pd18j; do
for freq in 2301000 2300000 1700000 1300000; do
for r in 1 2 3 4; do

std="--constraints haswell --experiment $exp --iterations 1 \
--overcommit enable --tag rc53-hsw-nn-ppnscaling-${freq}khz --tests deltafs --skipreads \
--extraopts '--cpu-freq=$freq --cpu-bind=cores' \
--env XX_IGNORE_DIRS=fields:hydro:rundata:names \
--env XX_SKIP_SAMP=1 \
--env XX_SKIP_SORT=1 \
--env XX_SKIP_PAPI=1 \
--env XX_NO_PRE_FLUSH=0 \
--env XX_NO_PRE_FLUSH_WAIT=0 \
--env XX_NO_PRE_FLUSH_SYNC=0 \
--env XX_BG_PAUSE=1 \
--env XX_SH_THREE_HOP=0 \
--env XX_HG_PROTO=bmi+tcp \
--env XX_ALWAYS_SHUFFLE=0 \
--env XX_RPC_RANDOM_FLUSH=1 \
--env XX_RPC_BUF=$((64*1024)) \
--env XX_RPC_DEPTH=2 \
--env XX_RECV_RADIX=0 \
--env XX_BYPASS_CH=1  \
--env XX_BYPASS_WRITE=1 \
--env XX_PARTICLE_ID_SIZE=11 \
--env XX_PARTICLE_SIZE=40 \
--env 'VPIC_EMU_OPTS=-t 7200' \
--env 'VPIC_EMU=preload-runner' \
--env 'VPIC_PRE='"

eval ../vpicexpt_gen.pl ${std} --run $r --dw off .

done
done
done

exit 0
