#!/bin/bash

# In this part we do the vpic exp using the new deltafs rc40 3-hop code
# on KNL processors.

# We keep the IO speed fixed at 5.33GiB/s per 32 KNL nodes,
# or 2.67MiB/s per KNL core. We don’t drop data.

for r in 1 2 3 4 5 6; do
# deltafs w/o memtable sort, 2 senders per receiver
std="--partition knl --constraints knl,quad,flat --experiment sc18l --iterations 1 \
--overcommit enable --core-spec 4 --tag rc40-knl-try3-3hop-unsorted-bindtonone-quad-2v1 --tests deltafs --skipreads \
--env XX_IGNORE_DIRS=fields:hydro:rundata:names \
--env XX_SKIP_SAMP=1 \
--env XX_SKIP_SORT=1 \
--env XX_NO_PRE_FLUSH=0 \
--env XX_NO_PRE_FLUSH_WAIT=0 \
--env XX_NO_PRE_FLUSH_SYNC=0 \
--env XX_IMD_RATELIMIT=5588910 \
--env XX_BG_PAUSE=1 \
--env XX_SH_THREE_HOP=1 \
--env XX_HG_PROTO=bmi+tcp \
--env XX_ALWAYS_SHUFFLE=1 \
--env XX_RECV_RADIX=1 \
--env XX_BYPASS_CH=1"

eval ../vpicexpt_gen.pl ${std} --extraopts "--cpu_bind=none" --run $r --dw bw .

done

exit 0
