#!/bin/bash

# In this part we do the vpic exp using the deltafs rc41 no-shuffle code
# with the read phase.

# We keep the IO speed fixed at 5.33GiB/s per 32 compute nodes,
# or 5.33MiB/s per core. We don’t drop data.

for r in 1 2 3 4 5 6 7 8; do
# deltafs w/o memtable sort
std="--constraints haswell --experiment sc18d --iterations 1 \
--overcommit enable --tag rc41-try1-nosh-unsorted --tests deltafs \
--env XX_IGNORE_DIRS=fields:hydro:rundata:names \
--env XX_SKIP_SAMP=0 \
--env XX_SKIP_SORT=1 \
--env XX_NO_PRE_FLUSH=0 \
--env XX_NO_PRE_FLUSH_WAIT=0 \
--env XX_NO_PRE_FLUSH_SYNC=0 \
--env XX_IMD_RATELIMIT=5588910 \
--env XX_BG_PAUSE=1 \
--env XX_BYPASS_SHUFFLE=1 \
--env XX_BYPASS_CH=1"

eval ../vpicexpt_gen.pl ${std} --run $r --dw bw .

done

exit 0
