#!/bin/bash

# In this part we evaluate the performance impact of particle sizes.

# We keep the IO speed fixed at 5.33GiB/s per 32 KNL nodes,
# or 2.67MiB/s per KNL core. We drop all data.

for sz in 8 1; do
for r in 6; do

std="--partition knl --constraints knl,quad,flat --experiment sc18l --iterations 1 \
--overcommit disable --core-spec 4 --tag rc47-knl-try6-s-1hop-ddr4-64k-${sz}byteparticle --tests deltafs --skipreads \
--extraopts '--cpu-bind=none --mem-bind=map_mem:0x0' \
--env XX_IGNORE_DIRS=fields:hydro:rundata:names \
--env XX_SKIP_SAMP=1 \
--env XX_SKIP_SORT=1 \
--env XX_NO_PRE_FLUSH=0 \
--env XX_NO_PRE_FLUSH_WAIT=0 \
--env XX_NO_PRE_FLUSH_SYNC=0 \
--env XX_BG_PAUSE=1 \
--env XX_SH_THREE_HOP=0 \
--env XX_HG_PROTO=bmi+tcp \
--env XX_ALWAYS_SHUFFLE=0 \
--env XX_RPC_BUF=$((64*1024)) \
--env XX_RECV_RADIX=0 \
--env XX_BYPASS_CH=1  \
--env XX_BYPASS_WRITE=1 \
--env XX_PARTICLE_ID_SIZE=8 \
--env XX_PARTICLE_SIZE=${sz} \
--env XX_HEX_FNAME=1 \
--env 'VPIC_EMU_OPTS=-t 7200' \
--env 'VPIC_EMU=preload-runner' \
--env 'VPIC_PRE='"

eval ../vpicexpt_gen.pl ${std} --run $r --dw off .

done
done

exit 0
