#!/bin/bash

# In this part we do a pass of standard vpic runs with different
# shufflers, and compare the read and write performance
# among 1-hop, 3-hop, and nosh (no shuffle).

# We keep the IO speed fixed at 5.33GiB/s per 32 compute nodes,
# or 5.33MiB/s per core. We don’t drop data.

for r in 7 8; do
# nosh
std="--constraints haswell --experiment sc18d --iterations 1 \
--overcommit enable --tag rc35-nosh --tests deltafs \
--env XX_IGNORE_DIRS=fields:hydro:rundata:names \
--env XX_SKIP_SAMP=0 \
--env XX_BYPASS_SHUFFLE=1 \
--env XX_BYPASS_CH=1 \
--env XX_IMD_RATELIMIT=5588910 \
--env XX_IMD_DROPDATA=0 \
--env XX_BF_BITS=12"

eval ../vpicexpt_gen.pl ${std} --run $r --dw bw .

# 1-hop
std="--constraints haswell --experiment sc18d --iterations 1 \
--overcommit enable --tag rc35-1hop --tests deltafs \
--env XX_IGNORE_DIRS=fields:hydro:rundata:names \
--env XX_SKIP_SAMP=0 \
--env XX_SH_THREE_HOP=0 \
--env XX_HG_PROTO=bmi+tcp \
--env XX_ALWAYS_SHUFFLE=0 \
--env XX_BYPASS_CH=1 \
--env XX_IMD_RATELIMIT=5588910 \
--env XX_IMD_DROPDATA=0 \
--env XX_BF_BITS=12"

eval ../vpicexpt_gen.pl ${std} --run $r --dw bw .

# 3-hop
std="--constraints haswell --experiment sc18d --iterations 1 \
--overcommit enable --tag rc353hop --tests deltafs \
--env XX_IGNORE_DIRS=fields:hydro:rundata:names \
--env XX_SKIP_SAMP=0 \
--env XX_SH_THREE_HOP=1 \
--env XX_HG_PROTO=bmi+tcp \
--env XX_ALWAYS_SHUFFLE=1 \
--env XX_BYPASS_CH=1 \
--env XX_IMD_RATELIMIT=5588910 \
--env XX_IMD_DROPDATA=0 \
--env XX_BF_BITS=12"

eval ../vpicexpt_gen.pl ${std} --run $r --dw bw .

done
