#!/bin/bash

export CRAYPE_LINK_TYPE="dynamic"
export CRAYOS_VERSION=6

module unload craype-hugepages2M

module load craype-mic-knl
module load PrgEnv-intel
# module load perftools
module load cmake

env CC=cc CXX=CC cmake \
-DCMAKE_INSTALL_PREFIX=/users/ccranor/jul18/r43k-papi \
-DCMAKE_BUILD_TYPE=RelWithDebInfo \
-DUMBRELLA_SKIP_TESTS=ON \
..

make papi-try
make scripts

exit 0
