#!/bin/bash

# There are strong-sclaing, shuffle-only runs.

for r in 1 2 3; do

std="--partition knl --constraints knl,quad,flat --experiment pd18a --iterations 1 \
--overcommit disable --tag rc49up2-knl-nn-strongscaling --tests deltafs --skipreads \
--extraopts '--cpu-bind=none --mem-bind=map_mem:0x0' \
--env XX_IGNORE_DIRS=fields:hydro:rundata:names \
--env XX_SKIP_SAMP=1 \
--env XX_SKIP_SORT=1 \
--env XX_SKIP_PAPI=1 \
--env XX_NO_PRE_FLUSH=0 \
--env XX_NO_PRE_FLUSH_WAIT=0 \
--env XX_NO_PRE_FLUSH_SYNC=0 \
--env XX_BG_PAUSE=1 \
--env XX_SH_THREE_HOP=0 \
--env XX_HG_PROTO=bmi+tcp \
--env XX_ALWAYS_SHUFFLE=0 \
--env XX_RPC_RANDOM_FLUSH=1 \
--env XX_RPC_BUF=$((64*1024)) \
--env XX_RPC_DEPTH=2 \
--env XX_RECV_RADIX=0 \
--env XX_BYPASS_CH=1  \
--env XX_BYPASS_WRITE=1 \
--env XX_PARTICLE_ID_SIZE=11 \
--env XX_PARTICLE_SIZE=40 \
--env 'VPIC_EMU_OPTS=-t 7200' \
--env 'VPIC_EMU=preload-runner' \
--env 'VPIC_PRE='"

eval ../vpicexpt_gen.pl ${std} --run $r --dw off .

done

exit 0
