#!/bin/bash

module add cmake gcc intel-mpi

cmake -DCMAKE_INSTALL_PREFIX=/users/ccranor/jun19/r67b \
-DCMAKE_BUILD_TYPE=RelWithDebInfo \
-DMERCURY_POST_LIMIT=OFF \
-DMERCURY_CHECKSUM=OFF \
-DMERCURY_NA_INITIALLY_ON="bmi;ofi;cci;sm" \
-DUMBRELLA_SKIP_TESTS=ON \
..

make

exit 0
