#!/bin/bash

# In this part we do the vpic exp using the deltafs rc44 3-hop code
# on KNL processors.

# We keep the IO speed fixed at 5.33GiB/s per 32 KNL nodes,
# or 2.67MiB/s per KNL core. We drop all data.

#   NOTE
# -----------
# Fixed 48MB memtable per receiver.
# Memory overcommit is disabled.
# Using quad,flat (no CPU binding)
# Using only DDR4.

for rx in 1 2 3; do  # From 2 senders per reciever to 8 senders per receiver
for r in 6; do
# deltafs w/o memtable sort, variable senders per receiver
std="--partition knl --constraints knl,quad,flat --experiment sc18l --iterations 1 \
--overcommit disable --core-spec 4 --tag rc44-knl-try2-u-3hop-ddr4-128k-rx$rx --tests deltafs --skipreads \
--env XX_IGNORE_DIRS=fields:hydro:rundata:names \
--env XX_SKIP_SAMP=1 \
--env XX_SKIP_SORT=1 \
--env XX_NO_PRE_FLUSH=0 \
--env XX_NO_PRE_FLUSH_WAIT=0 \
--env XX_NO_PRE_FLUSH_SYNC=0 \
--env XX_BG_PAUSE=1 \
--env XX_SH_THREE_HOP=1 \
--env XX_HG_PROTO=bmi+tcp \
--env XX_ALWAYS_SHUFFLE=1 \
--env XX_RPC_BUF=$((128*1024)) \
--env XX_RECV_RADIX=$rx \
--env XX_BYPASS_CH=1  \
--env XX_IMD_RATELIMIT=$((2794455*(2**$rx))) \
--env XX_IMD_DROPDATA=1 \
--env 'VPIC_EMU_OPTS=-t 3600' \
--env 'VPIC_EMU=preload-runner' \
--env 'VPIC_PRE='"

eval ../vpicexpt_gen.pl ${std} --extraopts "--cpu-bind=none --mem-bind=map_mem:0x0" --run $r --dw off .

done
done

exit 0
