#!/bin/bash

# In this part we do the vpic exp using the new deltafs rc40 1-hop code
# on KNL processors.

# We keep the IO speed fixed at 5.33GiB/s per 32 KNL nodes,
# or 2.67MiB/s per KNL core. We don’t drop data.

for sz in 32 64 128; do
for r in 6; do
# deltafs w/o memtable sort, full receiver
std="--partition knl --constraints knl,snc4,flat --experiment sc18l --iterations 1 \
--overcommit enable --core-spec 4 --tag rc40-knl-try5-unsorted-${sz}k --tests deltafs --skipreads \
--env XX_IGNORE_DIRS=fields:hydro:rundata:names \
--env XX_SKIP_SAMP=1 \
--env XX_SKIP_SORT=1 \
--env XX_NO_PRE_FLUSH=0 \
--env XX_NO_PRE_FLUSH_WAIT=0 \
--env XX_NO_PRE_FLUSH_SYNC=0 \
--env XX_IMD_RATELIMIT=2794455 \
--env XX_BG_PAUSE=1 \
--env XX_SH_THREE_HOP=0 \
--env XX_HG_PROTO=bmi+tcp \
--env XX_ALWAYS_SHUFFLE=0 \
--env XX_RPC_BUF=$(($sz*1024)) \
--env XX_BYPASS_CH=1"

eval ../vpicexpt_gen.pl ${std} --run $r --dw bw .

done
done

exit 0
