#!/bin/bash

# In this part we do a pass of rate-limiting data-dropping 1-hop runs,
# and compare the performance of different outstanding rpcs.

# We keep the IO speed fixed at 5.33GiB/s per 32 compute nodes,
# or 5.33MiB/s per core.

for out in 2 1; do
for r in 1 2 3 4 5 6; do
std="--constraints haswell --experiment sc18d --iterations 1 \
--overcommit enable --tag rc35-try1-${out}outs --tests deltafs --skipreads \
--env XX_IGNORE_DIRS=fields:hydro:rundata:names \
--env XX_SKIP_SAMP=1 \
--env XX_SH_THREE_HOP=0 \
--env XX_HG_PROTO=bmi+tcp \
--env XX_RPC_DEPTH=$out \
--env XX_ALWAYS_SHUFFLE=0 \
--env XX_BYPASS_CH=1 \
--env XX_IMD_RATELIMIT=5588910 \
--env XX_IMD_DROPDATA=1 \
--env XX_BF_BITS=12"

eval ../vpicexpt_gen.pl ${std} --run $r --dw bw .

done
done
